services:
  app:
    depends_on:
      - db
    build: .
    ports:
      - 8080:8080
    networks:
      - app-network

  db: 
    image: postgres:latest
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: s368982
      POSTGRES_PASSWORD: BxNwuaNnWgFyrROJ
      POSTGRES_DB: studs
    networks:
      - app-network
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - 6969:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-db-data:
